server:
  port: 0
spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411
    enable: true

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/