server:
  port: 0
spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411
    enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mq:
    queue:
       name: catalog
       serie: 'serieSender'
       movie: 'movieSender'
    exchange: 'catalog_event_exchange'
    key-routing: "catalog_event_key_routing"
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/