server:
  port: 0
spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411
    enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mq:
    queue:
       name: catalog
       serie: 'serieSender'
       movie: 'movieSender'
    exchange: 'catalog_event_exchange'
    key-routing: "catalog_event_key_routing"
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: backup
      port: 27017
  resilience4j:
    circuitbreaker:
      instances:
        movie:
          register-health-indicator: true
          sliding-window-type: COUNT_BASED
          sliding-window-size: 10
          minimum-number-of-calls: 5
          permitted-number-of-calls-in-half-open-state: 3
          wait-duration-in-open-state: 5s
          failure-rate-threshold: 50
          automatic-transition-from-open-to-half-open-enabled: true
        serie:
          register-health-indicator: true
          sliding-window-type: COUNT_BASED
          sliding-window-size: 10
          minimum-number-of-calls: 5
          permitted-number-of-calls-in-half-open-state: 3
          wait-duration-in-open-state: 5s
          failure-rate-threshold: 50
          automatic-transition-from-open-to-half-open-enabled: true

    retry:
      instances:
        moviesRetry:
          max-retries: 3
          wait-duration: 500ms
          retry-exception-predicate: io.github.resilience4j.circuitbreaker.CallNotPermittedException
        seriesRetry:
          max-retries: 3
          wait-duration: 500ms
          retry-exception-predicate: io.github.resilience4j.circuitbreaker.CallNotPermittedException

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/