server:
  port: 0

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  zipkin:
    base-url: http://localhost:9411
    enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mq:
    queue:
       name: serieSender
    exchange: 'serie_event_exchange'
    key-routing: "serie_event_key_routing"

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/